### ISSUE TITLE
WallFollow uses max_runtime Coverage Server Example uses max_duration

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_sim#130]
It was a little confusing to find the action goal parameter max_runtime for the new wall_follow action, after using max_duration with the coverage server example.

```
ros2 action send_goal /wall_follow irobot_create_msgs/action/WallFollow "{follow_side: 1, max_runtime:{sec: 1000,nanosec: 0}}"

ros2 action send_goal /coverage create3_examples_msgs/action/Coverage "{explore_duration:{sec: 500, nanosec: 0}, max_duration:{sec: 1000,nanosec: 0}}"

```

BTW, the wall_follow action is so cool - Thank you, Thank you!

**Comment by justinIRBT** [comment]
@alsora Should we be consistent between the two?  It would be easier to change the example goal.

**Comment by alsora** [comment]
Yes, I agree on changing the example.

**Comment by slowrunner** [comment]
Ok - I'll open it on the example.  Thanks.
