### ISSUE TITLE
Package 'irobot_create_gazebo_bringup' not found

### ISSUE THREAD

**Issue by carlitoselmago** [iRobotEducation/create3_sim#191]
When running the launch command after following all steps
```
ros2 launch irobot_create_gazebo_bringup create3_gazebo_aws_small.launch.py
```

I get 
```
Package 'irobot_create_gazebo_bringup' not found: "package 'irobot_create_gazebo_bringup' not found, searching: ['/home/ubuntu/create3_ws/install/irobot_create_toolbox', '/home/ubuntu/create3_ws/install/irobot_create_description', '/home/ubuntu/create3_ws/install/irobot_create_control', '/opt/ros/galactic']"

```
Running on Ubuntu 20.04.5 LTS on a virtual machine

**Comment by alsora** [comment]
Have you built the code from sources or installed from debian packages?
can you provide your steps to reproduce?

**Comment by carlitoselmago** [comment]
installed from debian packages , today it actually worked, i believe I might have done something wrong while coping multiple lines of install commands at once.
