### ISSUE TITLE
Sim doesn't realize goals are complete - and no data on /odom

### ISSUE THREAD

**Issue by tay-bird** [iRobotEducation/create3_sim#201]
**Describe the bug**
I'm running create3_sim in a Humble docker environment. There are no messages published on `/odom` and I'm seeing some goals behaving unexpectedly: when a goal involves rotating or driving, that behaviour continues forever without stopping.

I'm pretty new to ros + the create3, but it seems like the sim is supposed to publish to `/odom` but isn't, which causes the goals to never complete. Is this a bug in the sim, or did I set something up wrong?

**To Reproduce**

1. Create `Dockerfile` from the [create3-docker example](https://github.com/iRobotEducation/create3-docker/blob/main/create3-humble/Dockerfile):
```
docker build -t create3-sim:latest
```

2. Run the new Dockerfile:
```
docker run -it create3-sim:latest bash
```

3. In the container, start the sim:
```
source /opt/ros/humble/setup.bash
source /root/create3_ws/install/local_setup.bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py
```

4. In a new terminal, run a second copy of the image.
```
docker run -it create3-sim:latest bash
```

5. In the second container, tell the sim to undock and navigate to position:
```
apt update && apt install -y ros-${ROS_DISTRO}-irobot-create-msgs
ros2 action send_goal /undock irobot_create_msgs/action/Undock "{}"
ros2 action send_goal /navigate_to_position irobot_create_msgs/action/NavigateToPosition "{achieve_goal_heading: true,goal_pose:{pose:{position:{x: 1,y: 0.2,z: 0.0}, orientation:{x: 0.0,y: 0.0, z: 0.0, w: 1.0}}}}"
```

6. Observe the sim undock successfully, but get stuck spinning forever trying to find the goal heading.
 
7. Observe the odom topic not publishing:
```
ros2 topic echo /odom
```

**Expected behavior**
- The sim robot should rotate to its goal heading, move towards the defined position, and stop.
- The `/odom` topic should have data published to it.

**Screenshots**
![Screen Shot 2023-02-12 at 11 20 33 AM](https://user-images.githubusercontent.com/2468680/218332395-e1e93772-b26a-4d1a-8802-184ab4f3f1ee.png)
![Screen Shot 2023-02-12 at 11 21 48 AM](https://user-images.githubusercontent.com/2468680/218332413-7e8a7a4a-bd12-4da1-bdd9-8b2dcb5b9e5c.png)

**Additional context**
In rviz, there are error messages for left_wheel and right_wheel that no transforms to odom are present.

**Comment by alsora** [comment]
Is your issue consistently reproducible?
Can you post the log that you see in the terminal where you are running `ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py` ?

**Comment by jonliberal** [comment]
I'm facing exactly the same issue on my Ubuntu 22.04 machine running ROS2 Humble. The Dock and Undock goals work fine however.

**Comment by alsora** [comment]
@jonliberal what is the "same exact issue" that you are referring to?

**Comment by jonliberal** [comment]
> @jonliberal what is the "same exact issue" that you are referring to?

I'm not seeing data published to /odom topic. And Drive Goals (tested Drive Arc, Rotate Angle, Navigate to Position) are never completed: the robot initiates movement (e.g. rotate around itself for Rotate Angle) and never stops.

**Comment by alsora** [comment]
Ok, it's strange then that you are able to dock/undock successfully.
Please post a log from the terminal where you are running the gazebo launch file.
We will try to reproduce and look for a fix.

**Comment by alsora** [comment]
We are looking into this problem and we just merged this PR which should fix some of the issues
https://github.com/iRobotEducation/create3_sim/pull/206

**Comment by alsora** [comment]
We pushed additional fixes as part of this PR https://github.com/iRobotEducation/create3_sim/pull/200.
Please, let us know if everything works as expected now.
