### ISSUE TITLE
Issue with rendering engine in the urdf

### ISSUE THREAD

**Issue by suchetanrs** [iRobotEducation/create3_sim#235]
**Describe the bug**
The RPLidar simulation in turtlebot4 does not work well if the render engine is set to ogre. If it is changed to ogre2, it starts to work properly.

**To Reproduce**
Follow the setup instructions here https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_simulator.html

Run ros2 launch turtlebot4_gz_bringup turtlebot4_gz.launch.py

Add the visualize lidar plugin on gazebo and visualise the rplidar topic.

**Expected behavior**
Obstacles should be detected well.

**Screenshots**
With ogre render engine
![image](https://github.com/user-attachments/assets/95a5a4e0-9512-4614-aec6-6500d7526b40)

With ogre2 render engine
![image](https://github.com/user-attachments/assets/6a515887-788d-45d5-ba4e-e134a7bbf3d1)

**Comment by suchetanrs** [comment]
Should I raise a PR for this with the render engine changed to ogre2? 
If yes, to which target branch should I raise one?

Thanks!

**Comment by alsora** [comment]
@suchetanrs this appears to be an issue with the turtlebot simulation and not related with the create 3.
I suggest you to re-open the ticket in this repository: https://github.com/turtlebot/turtlebot4_simulator
